### ISSUE TITLE
Would you add Washington, D.C. to the list of state names?

### ISSUE THREAD

**Issue by gunterja** [datasets-io/us-states-abbr-names#2]

**Comment by kgryte** [comment]
Thanks for asking. The answer is no, as the geographical area in which Washington, D.C., resides is a federal district not a state. Augmenting the hash with other abbreviations/names can happen easily enough in userland.

**Comment by gunterja** [comment]
While that is correct, I would imagine the most common usage of your service is for shipping address/location purposes, and there are a number of folks living in DC(around 650k) who need things shipped to them. Just a thought.  :)

I already implemented a change on our end and removed the dependency but I thought it was worth mentioning to potentially make your service more useful. Thanks for the quick response!

Best,

Jeremy Gunter Software Engineer
Ackmann & Dickenson Inc.

Office 612.486.5100 Cell 214.325.1357 Fax 612.486.5115
www.ackmanndickenson.com http://www.ackmanndickenson.com/

**Comment by kgryte** [comment]
The shipping argument could be made for the US Virgin Islands (VI), Puerto Rico (PR), Guam (GU), American Samoa (AS), and the Northern Mariana Islands (MP), which have a combined population of roughly `4` million. Not to mention the Marshall Islands (MS), Micronesia (FM), and Palau (PW).

What you want is not `us-states-abbr-names` but `us-territories-postal-codes-names`, which is a different dataset.

**Comment by gunterja** [comment]
Thank you for the recommendation :)
